#' @title Set Saved Parameters - LGD
#'
#' @description Returns a character vector of parameters to be saved by JAGS in the Lower Granite version of DABOM
#'
#' @author Kevin See
#'
#' @param time_varying Should the initial movement probabilities be time-varying? Default value is \code{FALSE}
#'
#' @export
#' @return NULL
#' @examples setSavedParams()

setSavedParams_LGD = function(time_varying = F) {

  # start with movement probabilities
  my_params = c('p_pop_main',
                'p_pop_Asotin',
                'p_pop_AsoUpp',
                'p_pop_Lapwai',
                'p_pop_Potlatch',
                'p_pop_KHS',
                'p_pop_HLM',
                'p_pop_Wallowa',
                'p_pop_UppGR',
                'p_pop_Imnaha',
                'p_pop_UppImn',
                'p_pop_ImnWeir',
                'p_pop_SFS',
                'p_pop_LowLemhi',
                'p_pop_UpLemhi',
                'p_pop_UpSalm',
                'phi_mtr',
                'phi_utr',
                'phi_tuch',
                'phi_acb',
                'phi_web',
                'phi_josepc',
                'phi_iml',
                'phi_ir5',
                'phi_lakec',
                'phi_johnsc',
                'phi_str',
                'phi_btm',
                'phi_btu',
                'phi_usi')

  # add detection probabilities
  my_params = c(my_params,
                'ACMA0_p',
                'ACMB0_p',
                'GEORGC_p',
                'ASOTIC_p',
                'ACB_p',
                'AFCA0_p',
                'AFCB0_p',
                'CCAA0_p',
                'CCAB0_p',
                'LTR_p',
                'MTR_p',
                'UTR_p',
                'TUCH_p',
                'ALMOTC_p',
                'ALPOWC_p',
                'PENAWC_p',
                'TENMC2_p',
                'LAPA0_p',
                'LAPB0_p',
                'SWTA0_p',
                'SWTB0_p',
                'WEBA0_p',
                'WEBB0_p',
                'MISA0_p',
                'MISB0_p',
                'JUL_p',
                'HLMA0_p',
                'HLMB0_p',
                'POTREF_p',
                'POTRWF_p',
                'KHSA0_p',
                'KHSB0_p',
                'LBEARC_p',
                'BIGBEC_p',
                'PCMA0_p',
                'PCMB0_p',
                'LC1_p',
                'LC2_p',
                'SC1_p',
                'SC2B0_p',
                'SC2A0_p',
                'CLC_p',
                'KOOS_p',
                'LRL_p',
                'FISTRP_p',
                'SW1_p',
                'JOCA0_p',
                'JOCB0_p',
                'JOSEPC_p',
                'WR1_p',
                'WALH_p',
                'LOSTIW_p',
                'BCANF_p',
                'LOOKGC_p',
                'UGR_p',
                'CCWA0_p',
                'CCWB0_p',
                'CATHEW_p',
                'GRANDW_p',
                'COCA0_p',
                'COCB0_p',
                'IR1_p',
                'IR2_p',
                'BSCA0_p',
                'BSCB0_p',
                'CMPA0_p',
                'CMPB0_p',
                'HORS3C_p',
                'LSHEEF_p',
                'IR3A0_p',
                'IR3B0_p',
                'CZYA0_p',
                'CZYB0_p',
                'FREEZC_p',
                'IR4A0_p',
                'IR4B0_p',
                'MAHOGC_p',
                'IMLA0_p',
                'IMLB0_p',
                'IMNAHW_p',
                'IR5A0_p',
                'IR5B0_p',
                'GUMBTC_p',
                'DRY2C_p',
                'RAPH_p',
                'SFG_p',
                'ESSA0_p',
                'ESSB0_p',
                'JOHNSC_p',
                'KRS_p',
                'STR_p',
                'ZENA0_p',
                'ZENB0_p',
                'LAKEC_p',
                'TAYA0_p',
                'TAYB0_p',
                'NFSA0_p',
                'NFSB0_p',
                'CRCA0_p',
                'CRCB0_p',
                'LLRA0_p',
                'LLRB0_p',
                'AGCA0_p',
                'AGCB0_p',
                'KENA0_p',
                'KENB0_p',
                'HYCA0_p',
                'HYCB0_p',
                'LRWA0_p',
                'LRWB0_p',
                'WPCA0_p',
                'WPCB0_p',
                'BHCA0_p',
                'BHCB0_p',
                'LLSA0_p',
                'LLSB0_p',
                'BTLA0_p',
                'BTLB0_p',
                'BTMA0_p',
                'BTMB0_p',
                'BTUA0_p',
                'BTUB0_p',
                'LCLA0_p',
                'LCLB0_p',
                'LB8A0_p',
                'LB8B0_p',
                'LBSA0_p',
                'LBSB0_p',
                'CACA0_p',
                'CACB0_p',
                'HECA0_p',
                'HECB0_p',
                'USE_p',
                'USI_p',
                'VC1_p',
                'VC2_p',
                'YFKA0_p',
                'YFKB0_p',
                'STL_p',
                'SALEFT_p',
                'PAHH_p')

  if(time_varying) {
    my_params = c(my_params,
                  'sigma_rw')
  }

  return(my_params)
}
