#' @title Set Saved Parameters - PRA
#'
#' @description Returns a character vector of parameters to be saved by JAGS in the Priest Rapids version of DABOM
#'
#' @author Kevin See
#'
#' @param time_varying Should the initial movement probabilities be time-varying? Default value is \code{FALSE}
#'
#' @export
#' @return NULL
#' @examples setSavedParams_PRA()

setSavedParams_PRA = function(time_varying = F) {

  # start with movement probabilities
  my_params = c('p_pop_PRA',
                'p_pop_RIA',
                'p_pop_LWE',
                'p_pop_ICL',
                'p_pop_TUM',
                'p_pop_UWE',
                'p_pop_RRF',
                'p_pop_ENL',
                'p_pop_WEA',
                'p_pop_LMR',
                'p_pop_MRC',
                'p_pop_OKL',
                'p_pop_ZSL',
                'p_pop_dwn',
                'p_pop_PRV',
                'phi_icu',
                'phi_peu',
                'phi_chu',
                'phi_nau',
                'phi_enm',
                'phi_ens',
                'phi_enf',
                'phi_meth',
                'phi_twispw',
                'phi_cru',
                'phi_wfc',
                'phi_sa0',
                'phi_obf')

  # add detection probabilities
  my_params = c(my_params,
                'RIA_p',
                'CLK_p',
                'LWEB0_p',
                'LWEA0_p',
                'MCLB0_p',
                'MCLA0_p',
                'PESB0_p',
                'PESA0_p',
                'PEUB0_p',
                'PEUA0_p',
                'CHMB0_p',
                'CHMA0_p',
                'ICLB0_p',
                'ICLA0_p',
                'LNFB0_p',
                'LNFA0_p',
                'ICMB0_p',
                'ICMA0_p',
                'ICUB0_p',
                'ICUA0_p',
                'TUM_p',
                'CHWB0_p',
                'CHWA0_p',
                'CHLB0_p',
                'CHLA0_p',
                'CHUB0_p',
                'CHUA0_p',
                'UWE_p',
                'NALB0_p',
                'NALA0_p',
                'NAUB0_p',
                'NAUA0_p',
                'WTLB0_p',
                'WTLA0_p',
                'LWNB0_p',
                'LWNA0_p',
                'RRF_p',
                'ENLB0_p',
                'ENLA0_p',
                'RCTB0_p',
                'RCTA0_p',
                'EHLB0_p',
                'EHLA0_p',
                'ENAB0_p',
                'ENAA0_p',
                'MADB0_p',
                'MADA0_p',
                'ENMB0_p',
                'ENMA0_p',
                'ENSB0_p',
                'ENSA0_p',
                'ENFB0_p',
                'ENFA0_p',
                'WVTB0_p',
                'WVTA0_p',
                'WEA_p',
                'LMRB0_p',
                'LMRA0_p',
                'GLCB0_p',
                'GLCA0_p',
                'LBCB0_p',
                'LBCA0_p',
                'MRCB0_p',
                'MRCA0_p',
                'BVCB0_p',
                'BVCA0_p',
                'TWRB0_p',
                'TWRA0_p',
                'TWISPW_p',
                'CRWB0_p',
                'CRWA0_p',
                'CRUB0_p',
                'CRUA0_p',
                'SCPB0_p',
                'SCPA0_p',
                'MSHB0_p',
                'MSHA0_p',
                'METHB0_p',
                'METHA0_p',
                'MRWB0_p',
                'MRWA0_p',
                'WFC_p',
                'FST_p',
                'OKLB0_p',
                'OKLA0_p',
                'LLCB0_p',
                'LLCA0_p',
                'SA1B0_p',
                'SA1A0_p',
                'SA0B0_p',
                'SA0A0_p',
                'OMKB0_p',
                'OMKA0_p',
                'OBF_p',
                'WAN_p',
                'JOH_p',
                'TNK_p',
                'AEN_p',
                'BPCB0_p',
                'BPCA0_p',
                'ANTB0_p',
                'ANTA0_p',
                'WHS_p',
                'TON_p',
                'ZSLB0_p',
                'ZSLA0_p',
                'NMCB0_p',
                'NMCA0_p',
                'OKIB0_p',
                'OKIA0_p',
                'OKCB0_p',
                'OKCA0_p',
                'BelowJD1_p',
                'JD1B0_p',
                'JD1A0_p',
                'TMF_p',
                'PRV_p',
                'HSTB0_p',
                'HSTA0_p',
                'MDRB0_p',
                'MDRA0_p',
                'ICHB0_p',
                'ICHA0_p',
                'PROB0_p',
                'PROA0_p',
                'RSHB0_p',
                'RSHA0_p',
                'PRHB0_p',
                'PRHA0_p')

  if(time_varying) {
    my_params = c(my_params,
                  'sigma_rw')
  }

  return(my_params)
}
